# Generated by Django 5.2.1 on 2025-05-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('Register', models.IntegerField(primary_key='Register', serialize=False)),
                ('bookname', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('Dop', models.DateField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
